import { IListOption } from '@components/UI/organism/MultipleSelectionEntry/MultipleSelectionEntry.interface'

export const selectedValuesDemo: IListOption[] = []

export const listOptionsDemo: IListOption[] = [
  { id: 1, name: 'Administración y oficina' },
  { id: 16, name: 'Bodega, logística y transporte' },
  { id: 26, name: 'Call center, telemercadeo, BPO y afines' },
  { id: 27, name: 'Compras y comercio exterior' },
  { id: 31, name: 'Comunicación y Periodismo' },
  { id: 21, name: 'Construcción e infraestructura' },
  { id: 4, name: 'Contabilidad, finanzas, impuestos y afines' },
  { id: 5, name: 'Deporte y recreación' },
  { id: 6, name: 'Derecho, Asesoría y afines' },
  { id: 28, name: 'Dirección y Gerencia' },
  { id: 7, name: 'Diseño, arquitectura, artes gráficas y afines' },
  { id: 22, name: 'Docencia, educación, licenciaturas y afines' },
  { id: 8, name: 'Economía, estadística, matemáticas y afines' },
  { id: 9, name: 'Gastronomía, bebidas/alimentos y restaurantes' },
  { id: 10, name: 'Hotelería y turismo' },
  { id: 11, name: 'Idiomas y traducción' },
  { id: 12, name: 'Industria de la aviación y afines' },
  { id: 14, name: 'Ingenierías' },
  { id: 15, name: 'Inversiones y mercado bursátil' },
  { id: 29, name: 'Investigación y Calidad' },
  { id: 30, name: 'Mantenimiento y Reparaciones' },
  { id: 17, name: 'Mecánica y sector automotriz' },
  { id: 18, name: 'Medicina, sector de la salud y Ciencias' },
  { id: 3, name: 'Mercadeo y Publicidad' },
  { id: 19, name: 'Otras' },
  { id: 20, name: 'Política, ONG, sector Gobierno y fundaciones' },
  { id: 13, name: 'Producción, Operarios y Manufactura' },
  { id: 2, name: 'Recursos Humanos' },
  { id: 24, name: 'Servicio al cliente y afines' },
  { id: 32, name: 'Servicios generales, Aseo y Seguridad' },
  { id: 23, name: 'Software, informática y telecomunicaciones' },
  { id: 34, name: 'Transportador de Energía' },
  { id: 25, name: 'Ventas' },
  { id: 33, name: 'Zoología, Veterinario y sector Agroindustrial' }
]
