export { default as spinnerBarsGray } from '../assets/gif/spinnerBarsGray.gif'
export { default as SwipeLeft } from '../assets/gif/SwipeLeft.gif'
export { default as SwipeRight } from '../assets/gif/SwipeRight.gif'
export { default as NoData } from '../assets/gif/noData.gif'
export { default as Waiting } from '../assets/gif/waiting.gif'
