import 'styled-components'

// Generated by https://quicktype.io

export interface Colors {
  primaryColors: PrimaryColors
  disabledColors: DisabledColors
  alertColors: AlertColors
  textColors: TextColors
  primary: string
  contrastColor: string
  primaryLight1: string
  breadcrumbsColor: string
  black: string
  white: string
  primary1: string
  primary2: string
  primary3: string
  primary4: string
  primary5: string
  primary7: string
  positive: string
  warning: string
  information: string
  negative: string
  $gray1: string
  $gray2: string
  $gray3: string
  $gray4: string
  $gray5: string
  $gray6: string
  $grayText: string
  $grayTitle: string
  $graySubtitle: string
  $grayDark: string
}

export interface AlertColors {
  red: string
  redHover: string
  redBorder: string
  yellow: string
  yellowHover: string
  yellowBorder: string
  blue: string
  blueHover: string
  blueBorder: string
}

export interface DisabledColors {
  gray: string
  gray2: string
  gray3: string
}

export interface PrimaryColors {
  white: string
  green: string
  greenHover: string
  greenBorder: string
  purple: string
  purpleHover: string
  purpleBorder: string
  blue: string
  blueHover: string
  blueBorder: string
}

export interface TextColors {
  black: string
  disable: string
  blue: string
}

export interface Size {
  s1: number
  s2: number
  s3: number
  m1: number
  m2: number
  m3: number
  l1: number
  l2: number
  l3: number
}

export interface Spacing {
  padding: Padding
  borderRadius: BorderRadius
}

export interface BorderRadius {
  small: number
  default: number
}

export interface Padding {
  small: number
  medium: number
  large: number
}

export interface Weight {
  regular: string
  bold: string
  extrabold: string
  black: string
}

interface IPalette {
  main: string
  contrastText: string
}
declare module 'styled-components' {
  export interface DefaultTheme {
    colors: Colors
    weight: Weight
    spacing: Spacing
    size: Size
  }
}
